name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Apt Update
      run: apt update

    - name: Install build tools
      run: apt install -y build-essential

    - name: Raku version
      run: raku -v

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    - name: Build the helper
      run: zef build -v --debug .
      
    - name: Run tests
      run: zef test -v --debug .
